language: python
python:
- '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test --verbosity=2
  - coverage report -m
  - coveralls --verbose
